### ISSUE TITLE
Handler flow

### ISSUE THREAD

**Issue by gedw99** [Karimerto/natsrouter#1]
I read the docs and I was wondering if it’s possible to setup a router to have a handler that then sends a message into another router .

the use case example is that I have a proto or json message and I need the first route to process it and the output from that needs to piped to another route.

It’s basically pipeline processing .

In the end I can then have simple golang binaries that are invoked using with exec shell calls. Each binary supports std out and std in .

I just realised that what I need is to add a provider to the router that can take the message and invoke the binary and pass in the message .

**Comment by Karimerto** [comment]
I suppose that is pretty straightforward. You could setup one router to listen on subject "foo" and the second router to listen on "foo_2nd". When the first router receives a request, you do your processing and send another request to "foo_2nd". Second router does whatever it needs, sends back a response which is received by the first router and that in turn sends the response back to the original requestor.

It does sound perhaps a bit superfluous, but I can imagine some valid uses cases for this type of functionality.

I think you could also use pipes, if you so desire, by mashaling the nats.Msg as bytes and pushing that through a pipe. However then the second server/router has to be the one to send the reply. I have not tested this, but in theory it could be possible. Not sure what NATS has to say about the reply coming from a different client, but this might be interesting to test.

**Comment by gedw99** [comment]
Closing as was more a question than an issue.

great package
